// 地块类型枚举
export enum TILE_TYPE_ENUM {
  WALL_ROW = "WALL_ROW",
  WALL_COLUMN = "WALL_COLUMN",
  WALL_LEFT_TOP = "WALL_LEFT_TOP",
  WALL_LEFT_BOTTOM = "WALL_LEFT_BOTTOM",
  WALL_RIGHT_TOP = "WALL_RIGHT_TOP",
  WALL_RIGHT_BOTTOM = "WALL_RIGHT_BOTTOM",
  CLIFF_LEFT = "CLIFF_LEFT",
  CLIFF_RIGHT = "CLIFF_RIGHT",
  CLIFF_CENTER = "CLIFF_CENTER",
  FLOOR = "FLOOR",
}

// 事件枚举
export enum EVENT_ENUM {
  NEXT_LEVEL = "NEXT_LEVEL",
  PLAYER_CTRL = "PLAYER_CTRL",
}

// 控制器枚举
export enum CONTROLLER_ENUM {
  TOP = "TOP",
  BOTTOM = "BOTTOM",
  LEFT = "LEFT",
  RIGHT = "RIGHT",
  TURNLEFT = "TURNLEFT",
  TURNRIGHT = "TURNRIGHT",
}

// 状态机参数类型枚举
export enum FSM_PARAMS_TYPE_ENUM {
  TRIGGER = "TRIGGER",
  NUMBER = "NUMBER",
}

// 状态机参数名称枚举
export enum PARAME_NAME_ENUM{
  IDLE = "IDLE",
  TURNLEFT = "TURNLEFT",
}
