// 地块类型枚举
export enum TILE_TYPE_ENUM {
  WALL_ROW = "WALL_ROW",
  WALL_COLUMN = "WALL_COLUMN",
  WALL_LEFT_TOP = "WALL_LEFT_TOP",
  WALL_LEFT_BOTTOM = "WALL_LEFT_BOTTOM",
  WALL_RIGHT_TOP = "WALL_RIGHT_TOP",
  WALL_RIGHT_BOTTOM = "WALL_RIGHT_BOTTOM",
  CLIFF_LEFT = "CLIFF_LEFT",
  CLIFF_RIGHT = "CLIFF_RIGHT",
  CLIFF_CENTER = "CLIFF_CENTER",
  FLOOR = "FLOOR",
  WALL_NORMAL = "WALL_NORMAL",
}

// 事件枚举
export enum EVENT_ENUM {
  NEXT_LEVEL = "NEXT_LEVEL",
  PLAYER_CTRL = "PLAYER_CTRL",
}

// 控制器枚举
export enum CONTROLLER_ENUM {
  TOP = "TOP",
  BOTTOM = "BOTTOM",
  LEFT = "LEFT",
  RIGHT = "RIGHT",
  TURNLEFT = "TURNLEFT",
  TURNRIGHT = "TURNRIGHT",
}

// 状态机参数类型枚举
export enum FSM_PARAMS_TYPE_ENUM {
  TRIGGER = "TRIGGER",
  NUMBER = "NUMBER",
}

// 状态机参数名称枚举
export enum PARAMS_NAME_ENUM{
  IDLE = "IDLE",
  TURNLEFT = "TURNLEFT",
  DIRECTION = "DIRECTION",
}

// 方向枚举
export enum DIRECTION_ENUM{
  TOP = "TOP",
  BOTTOM = "BOTTOM",
  LEFT = "LEFT",
  RIGHT = "RIGHT",
}

// 实体状态枚举
export enum ENTITY_STATE_ENUM{
  IDLE = "IDLE",
  TURNLEFT = "TURNLEFT",
}

// 方向数字枚举
export enum DIRECTION_ORDER_ENUM{
  TOP = 0,
  BOTTOM = 1,
  LEFT = 2,
  RIGHT = 3,
}

export enum ENTITY_TYPE_ENUM{
  PLAYER = "PLAYER",
}
